"""Description of changes

Revision ID: f616f95b3069
Revises: 
Create Date: 2026-01-27 13:41:00.620375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f616f95b3069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_created_by'), 'forms', ['created_by'], unique=False)
    op.create_index(op.f('ix_forms_updated_by'), 'forms', ['updated_by'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_created_by'), 'form_fields', ['created_by'], unique=False)
    op.create_index(op.f('ix_form_fields_updated_by'), 'form_fields', ['updated_by'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('form_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_created_by'), 'form_submissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_form_submissions_updated_by'), 'form_submissions', ['updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_updated_by'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_created_by'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_form_fields_updated_by'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_created_by'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_forms_updated_by'), table_name='forms')
    op.drop_index(op.f('ix_forms_created_by'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
